### ISSUE TITLE
Support iOS 15 

### ISSUE THREAD

**Issue by dtantono** [gkasdorf/memmy#1]
Hi
I know there is iOS client out there for Lemmy. But, it only support iOS 16 and later. But, I hope this app will support iOS 15 and BTW, it is still relevant worldwide. What do you think?
https://gs.statcounter.com/ios-version-market-share/

**Comment by gkasdorf** [comment]
I have no issue targeting iOS 15.

I plan to have something available within the next week to put on TestFlight that includes the basic features of Lemmy. I'll be sure to decrease target version to iOS 15.
