### ISSUE TITLE
[Feature request] Swiping on posts similar to comments

### ISSUE THREAD

**Issue by adambowles** [gkasdorf/memmy#101]
Swiping for upvote, share etc. the same way we can currently swipe on comments

**Comment by gkasdorf** [comment]
This is on the list of things to do. Definitely something I am interested in myself, just have not gotten around to the implementation yet. Expect it here soon though.

**Comment by B0rax** [comment]
Looks like it was implemented in todays update

**Comment by gkasdorf** [comment]
Yup! There's a few more fixes that I had to make, these will be available in the next update in the coming hours. Thanks folks!
