### ISSUE TITLE
[BUG] Vote count starting at 2 instead of one.

### ISSUE THREAD

**Issue by hugpeter** [gkasdorf/memmy#103]
**Describe the bug**
When making a comment, and probably post too although i haven't tested posting, the vote total shows 2 instead of one. 

**To Reproduce**
Make a comment on a thread. 

**Expected behavior**
The vote count should start at 1. 

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: ios 16.5
 - Version 0.0.1 (52)

**Comment by gkasdorf** [comment]
https://github.com/gkasdorf/memmy/blob/c49f6b50dfa5990b1e7d91ca0b71aa713e86619e/components/ui/CommentItem2.tsx#LL381C51-L381C51 needs to be adjusted to determine what the original vote was when loading the comments. This would be an issue too if you voted one someones comment, refreshed the comments, then saw they had an additional upvote. Your vote from the API then one more we add.

Will fix. Thanks.

**Comment by gkasdorf** [comment]
Fixed in next update.
