### ISSUE TITLE
[BUG] some links fail, extra characters in page title

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#104]
**Describe the bug**
Some community links will not open correctly, extra odd characters are shown in title. 

**To Reproduce**
1. Go to https://lemmy.world/comment/104769 (from https://lemmy.world/post/45688)
2. Tap “Best of the Fediverse” or “Best Updates” link
3. Resulting page says “community not found” with an extra ) and @%5Bhttps in the title

**Expected behavior**
Community should open. 

**Screenshots**
![Broken link name](https://github.com/gkasdorf/memmy/assets/50390633/b467aefb-ed17-475d-ba39-afa0d9cdb091)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16.5
 - Version 0.0.1 (49)

(will add additional context when I can get to my desktop computer)

**Comment by gkasdorf** [comment]
Was just chatting with someone about some of these issues. I'm just going to take a different route with these. I'll have something tonight to fix this. Appreciate the report.

**Comment by JeremyLeland** [comment]
Could this be related to changes to the link-finding regex you mentioned on my other bug?

**Comment by JeremyLeland** [comment]
As of 0.0.1 (52), these links cause white screen crashes (like #96)

**Comment by gkasdorf** [comment]
I'm hopeful this is fixed here. https://github.com/gkasdorf/memmy/commit/0eb7289d6f0512effa4a23ec3fd1157d37f1921a

If you still run into more issues feel free to open this back up. Thank you!
