### ISSUE TITLE
Use a different colour for Original Poster (OP) comments in their post

### ISSUE THREAD

**Issue by MMeldrum** [gkasdorf/memmy#110]
**Is your feature request related to a problem? Please describe.**
It can be difficult to tell which comments/replies are from the original poster (OP).

**Describe the solution you'd like**
Use a different colour for the OP's username in the comments. (As per Apollo, and probably other 3PAs.)

Colour could also be used to highlight comments from moderators, etc.

**Comment by teflocarbon** [comment]
This is definitely planned and has already been mocked up.
Mockups are of course subject to change.

![Top Comments View Special - Light - Video](https://github.com/gkasdorf/memmy/assets/41776153/d1dd8873-f3c4-4190-a390-d8fcd0b6a19d)
![Top Comments View Special - Light - Video-1](https://github.com/gkasdorf/memmy/assets/41776153/b2fd8ab0-1d49-4b4d-86eb-9283b4079d56)

**Comment by MMeldrum** [comment]
Looks great! Are the mockups available? I don't want to waste your time looking at feature suggestions if you already have them planned.

**Comment by gkasdorf** [comment]
I've added something that will be in the next update. Thanks.
