### ISSUE TITLE
Comment upvote count is being shown instead of downvote count

### ISSUE THREAD

**Issue by isametry** [gkasdorf/memmy#113]
**Describe the bug**
For all comments, the displayed number of downvotes is equal to the number of upvotes, rather than the actual amount. This means that both numbers shown are the same.

Posts themselves are not affected.

**To Reproduce**
1. Browse any Lemmy or Kbin thread with comments (I have not checked others).

**Expected behavior**
The real downvote count should be shown.

**Screenshots**
In reality (judging by the website), the 2nd comment displayed here only has one downvote. The others should have 0 downvotes:

![IMG_8644 2](https://github.com/gkasdorf/memmy/assets/46103746/db6eeff3-9c47-4c6e-ad7d-3a6c2d150d2a)

After upvoting the second comment, the downvote number does not immediately sync:

![IMG_8642 2](https://github.com/gkasdorf/memmy/assets/46103746/1b98343a-f1c6-410e-9fca-c27c38100ef2)

Now let's refresh the page. The number on _both_ sides has increased by 1.

![IMG_8641 2](https://github.com/gkasdorf/memmy/assets/46103746/01e4b1ab-dbc5-476d-a8a0-35ca60bc4e67)

Remove the upvote now:

![IMG_8643 2](https://github.com/gkasdorf/memmy/assets/46103746/d383cb18-591d-4004-9b3a-ac00fcd54f0e)

And refresh once again:

![IMG_8644 2](https://github.com/gkasdorf/memmy/assets/46103746/39898ba5-5293-4779-989f-d193d2674638)

**Smartphone:**
 - Device: iPhone XR
 - OS: iOS 16.4.1
 - Memmy Version: 0.0.1 (53)

**Logs:**
[lemmy-debug.log](https://github.com/gkasdorf/memmy/files/11824261/lemmy-debug.log)

**Additional context**
My account is on lemmy.world.

**Comment by gkasdorf** [comment]
Fixed, sorry about that! Will push update soon.

**Comment by isametry** [comment]
Oh, that was quick! Thank you for your service 🫡

**Comment by gkasdorf** [comment]
🖖
