### ISSUE TITLE
[MEM-93] Support older iOS Versions

### ISSUE THREAD

**Issue by udomoody** [gkasdorf/memmy#118]
Hi,
would it be possible to support older iOS versions like iOS 14 or even 13? With Expo and these React Native apps I guess there shouldn't be a problem allow older versions as well.

<sub>[MEM-93](https://linear.app/memmyapp/issue/MEM-93/support-older-ios-versions)</sub>

**Comment by gkasdorf** [comment]
I can see how low I can target, I assumed that 15 was about as low as people go these days. Initial testing without even more optimization (which I'm working on now) shows memory usage of between 60-150 MB, so targeting older devices shouldn't be an issue there.

**Comment by gkasdorf** [comment]
We can see about simply changing the target version to 14, but if there is anything that breaks we cannot support those issues.

**Comment by p0358** [comment]
I notice that actually a lot of big React Native apps set their target to iOS 12 and still keep updating their apps. I think it's still supported and they do so because there's also a chunk of devices for which iOS 12 was the last supported version

**Comment by gkasdorf** [comment]
I'll change to 14 in this next update and see if things go well. I don't think it should break anything, but there are native APIs being used by some libs so can't promise anything.

**Comment by p0358** [comment]
Can you try 13? Lots of jailbreak users are also stuck on that version currently

**Comment by gkasdorf** [comment]
Sure. It will be available in a few hours probably.

**Comment by gkasdorf** [comment]
Going to be pushing an update now at target 13 🤘

**Comment by p0358** [comment]
Hmm, so regrettably it crashes currently on 13. Seems the missing library was introduced only on iOS 14 (realistically though I should update to 14 too probably...)

```
Date: 6/30/23, 5:00 PM
Process: Memmy
Bundle id: com.gkasdorf.memmyapp
Device: iPhone 6s Plus, iOS 13.5
Bundle version: 0.0.1

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: Library not loaded: /System/Library/Frameworks/UniformTypeIdentifiers.framework/UniformTypeIdentifiers
  Referenced from: /private/var/containers/Bundle/Application/0FA793EC-3EBB-4B7F-9A49-9CCF8145EF34/Memmy.app/Memmy
  Reason: image not found

Triggered by thread: 0
Thread name: 
Call stack:
0   dyld                          	0x0000000104f74f68 0x104f28000 + 315240     	// __abort_with_payload
1   dyld                          	0x0000000104f7bee8 0x104f28000 + 343784     	// abort_with_payload_wrapper_internal
2   dyld                          	0x0000000104f7bf18 0x104f28000 + 343832     
3   dyld                          	0x0000000104f7913c 0x104f28000 + 332092     	// invocation function for block in dyld::removeImage(ImageLoader*)
4   dyld                          	0x0000000104f2f1a4 0x104f28000 + 29092      	// dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*)
5   dyld                          	0x0000000104f29208 0x104f28000 + 4616       	// dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)
6   dyld                          	0x0000000104f29038 0x104f28000 + 4152       	// _dyld_start
```
