### ISSUE TITLE
[BUG] Invalid username or password

### ISSUE THREAD

**Issue by kavbrian21** [gkasdorf/memmy#130]
**Describe the bug**
I’m unable to login with my Lemmy account that works in the browser. My username and password are definitely correct: I have them stored in a password manager. I suspect the error may be related to password length or special characters.

**To Reproduce**
1. Enter existing account credentials

**Expected behavior**
Log in is successful.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 16
 - Version: 61

**Comment by gkasdorf** [comment]
Can you try changing your password and seeing if that resolved this? May be related to https://github.com/gkasdorf/memmy/issues/119

**Comment by gkasdorf** [comment]
Closing this for now. Let me know if the issue persists.

**Comment by kavbrian21** [comment]
With a new, shorter password, login now works ok.
