### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peruginiandrea** [gkasdorf/memmy#14]
**Describe the bug**
Image thumbnails not visible before tapping on them. Only white screen under the title.
**To Reproduce**
1. Go to 'front page'
2. See any post with a pic
3. See error

**Expected behavior**
Image should be visible already before tapping on the blank area.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: 17.0 dev beta 1
 - Version 0.0.1 (9)

**Comment by gkasdorf** [comment]
Yea, Im going to have to manage how the images get loaded. It tends to be issues with image retrieval from the specific instance that image is hosted on. I have a few ideas on how to manage it. I'll keep you posted. Thanks!

**Comment by peruginiandrea** [comment]
Damn, you’re blazing fast too haha

Good luck and thanks for what you’re doing!

**Comment by gkasdorf** [comment]
> Damn, you’re blazing fast too haha
> 
> Good luck and thanks for what you’re doing!

No problem! Could you do me a favor and let me know when this occurred? As in, we're you just slowly scrolling down the page or did you try to quickly scroll down like halfway or so?

**Comment by peruginiandrea** [comment]
> > Damn, you’re blazing fast too haha
> > 
> > Good luck and thanks for what you’re doing!
> 
> No problem! Could you do me a favor and let me know when this occurred? As in, we're you just slowly scrolling down the page or did you try to quickly scroll down like halfway or so? 

[link to video](https://www.veed.io/view/3deda520-c36b-42a9-9348-bbf31b08f175?panel=share)

**Comment by adjoseph16** [comment]
> > Damn, you’re blazing fast too haha
> > Good luck and thanks for what you’re doing!
> 
> No problem! Could you do me a favor and let me know when this occurred? As in, we're you just slowly scrolling down the page or did you try to quickly scroll down like halfway or so?

For me, it happens when I’m scrolling normally. There are certain posts it always seems to happen for, [such as this one.](https://lemmy.world/post/107926)

Here’s a screengrab too, if it helps:

https://github.com/gkasdorf/memmy/assets/78319881/7624d8e3-3884-4143-8ec4-36ce9e159bae

**Comment by gkasdorf** [comment]
@peruginiandrea @adjoseph16 Thanks for those. I see that it's actually a bit worse for you than what I've seen. I'll implement a fix. Likely will want to pre-load images before they come into the view.

**Comment by gkasdorf** [comment]
I'm going to add a debug log to record the last 50 or so image requests to the next build. Hopefully the fix I put in will relieve the issue, but if not, I'd appreciate it if you could send the log to me. I have a feeling the biggest reason I'm not seeing these issues is that I'm on one of the bigger instances (either lemmy.ml or lemmy.world), so nearly every image I am requesting is either from one of those instances or something else like Imgur.

**Comment by gkasdorf** [comment]
Found the issue. Looks like some servers might not be thumbnailing the images, which is the image I was trying to use in the feed view. I'll push an update with this fix alone to TestFlight now, since it's a rather big issue.

**Comment by gkasdorf** [comment]
https://github.com/gkasdorf/memmy/pull/16

**Comment by gkasdorf** [comment]
With improvements to performance as far as retrieving and caching images. https://github.com/gkasdorf/memmy/pull/17
