### ISSUE TITLE
[Feature Request] add clear option to search bar

### ISSUE THREAD

**Issue by Mori22** [gkasdorf/memmy#145]
**Is your feature request related to a problem? Please describe.**
Every single character typed in the search bar needs to be removed on its own. An option to clear all the content currently entered in the search bar would be a nice QoL improvement.

**Describe the solution you'd like**
Apollo is showing a small x on the right side of the search bar once something is inputed. The x clears the current content of the search bar.

**Additional context**
Implementation in Apollo
![image](https://github.com/gkasdorf/memmy/assets/31470057/5dc95b0e-7f7e-4d85-aece-507642cca16d)

**Comment by gkasdorf** [comment]
Done 👍
