### ISSUE TITLE
[BUG] Attempting to copy/share an image only shares its URL

### ISSUE THREAD

**Issue by PgBiel** [gkasdorf/memmy#146]
**Describe the bug**
Not sure if this was intentional or not, but, when attempting to share an image, I can only share its URL instead of the image itself. There surely might be uses in sharing an image's URL (and this could remain as an option somewhere, maybe in the share menu), but I believe the most common use case is to share the image itself (e.g. to WhatsApp to share to friends).

**To Reproduce**
1. Go to a post with an image, e.g. https://pawb.social/post/195693
2. Click on the image to show download/share options
3. Click on the share button to the right, displaying the share menu
4. Try to share the image to another app, or to copy it
5. Notice that the image's URL was shared/copied, not the image itself (despite, at times, advertising the image itself is being shared).

**Expected behavior**
The image itself should have been shared.

**Screenshots**
<details><summary>1. Entering the linked post</summary>
<p><image src="https://github.com/gkasdorf/memmy/assets/9021226/6bd54630-e6e3-4aa1-bede-0f3bb520dba7"/></p>
</details> 

<details><summary>2. Clicking on the image</summary>
<p>
<image src="https://github.com/gkasdorf/memmy/assets/9021226/f9fe37c8-61aa-47ee-8a35-ee5ada382c9a"/>
</p>
</details>

<details><summary>3. Clicking on the share button (it advertises the image is being shared)</summary>
<p>
<image src="https://github.com/gkasdorf/memmy/assets/9021226/fa7882a4-4385-4b77-bae7-958133e1221a"/>
</p>
</details>

<details><summary>4. Attempting to share (note just the URL was shared)</summary>
<p>
<image src="https://github.com/gkasdorf/memmy/assets/9021226/5ec8582f-9c14-4d75-ab57-c3a7ecefed3c"/>
</p>
</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.1.2
 - Version 70

**Logs:**
(no logs)

**Additional context**
As an Apollo immigrant, I have to say this app ticks all the right boxes. I was just a bit surprised by this behavior, as Apollo does it as one would expect (sharing the image itself).

Apollo also had a feature to download _videos_, but I guess that could be an eventual feature request instead.

**Comment by gkasdorf** [comment]
Going to fix this right now along with the animation issue https://github.com/gkasdorf/memmy/issues/156

**Comment by PgBiel** [comment]
Hello @gkasdorf, this bug still seems to be present on the latest versions (attempting to share images only shares their links on 0.0.2 (16)). Could you reopen this issue? Thanks.

**Comment by gkasdorf** [comment]
I don't know why this was closed actually but I'm literally working on it as we speak haha. Should be done in a few hours.

**Comment by PgBiel** [comment]
Gotcha! Sorry for bothering you haha. Thank you for the hard work, and for the great app!

**Comment by gkasdorf** [comment]
@PgBiel And...done https://github.com/Memmy-App/memmy/commit/3d1a0e05327558a02665fe5a1ff8f41235163a2a

**Comment by PgBiel** [comment]
Thank you!! I will make sure to test it and give feedback as soon as it's out 🙂.

**Comment by PgBiel** [comment]
Hey @gkasdorf, just wanted to give my feedback here. The feature is working! Thanks! Yay 🎉🎉🎉

Just one observation: it seems that there is oftentimes a somewhat large delay between clicking the share button and the share menu actually appearing (due to downloading the image, I imagine); do you think some sort of progress indicator (or at least a [throbber](https://en.wikipedia.org/wiki/Throbber)) could be added in (if that's not too hard to do)? Thanks again :)

**Comment by gkasdorf** [comment]
Haha literally just put this in the todo list. Will be in next update :)

**Comment by PgBiel** [comment]
Oh goodness... great minds think alike I guess? Hahaha

I will be on the wait! Thanks for all your effort, it is certainly appreciated :)
