### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by peruginiandrea** [gkasdorf/memmy#15]
**Describe the bug**
Minor visual bug: subscription list is see-through in some areas, more noticeable if pulling up.

**To Reproduce**
1. Go to subscriptions list
2. See as described above 

**Expected behavior**
No transparent gaps in between sections.

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/91615989/c2588af7-83a1-4ada-b53c-f1a0e867a5e8)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 17 dev beta 1
 - Version 0.0.1 (9)

**Comment by gkasdorf** [comment]
Yea, I actually only added the top options there temporarily. I will be adding a button similar to the "..." on a community view to select those options. That will get rid of the transparent areas. Thanks!

**Comment by gkasdorf** [comment]
Fixed this. I plan to do some  more rework to that dropdown once I get a proper screen for listing all of your subscribed communities done.
