### ISSUE TITLE
[BUG] Comments (but not replies) change order after scrolling

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#154]
**Describe the bug**
Scrolling far enough down and back to the top causes comments to re-arrange. Some of the initial comments will end up next to different replies, and with the wrong authors.

**To Reproduce**
1. Go to https://lemmy.world/post/573021
2. Note the first comment ("I like communities..." by @TurnItOff_OnAgain, followed by "It's almost like the /c/ stands..." by @BettyWhiteInHD)
3. Scroll down a ways, then scroll back to the top
4. Note the first comment text has changed (now says "What is wrong with using communities...", but still says @TurnItOff_OnAgain, and the reply is same as before)

**Expected behavior**
Should be same comments/authors as when we first loaded.

**Screenshots**
<<< will add momentarily from iOS >>>

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 16.5.1
 - Version 0.0.1 (70)

**Additional context**
I kept noticing what felt like the same comments over and over as I scrolled. I thought people were copying each others comments, but it looks like the text to some comments is actually jumping around when I scroll.

**Comment by JeremyLeland** [comment]
Before scrolling:
![IMG_0996](https://github.com/gkasdorf/memmy/assets/50390633/b48abdf4-2197-44be-bd3e-13322e5e0e85)

after scrolling down a ways then back up: 
![IMG_0997](https://github.com/gkasdorf/memmy/assets/50390633/b80707fa-6b5a-4fd0-95ae-732b8618c9ac)

**Comment by gkasdorf** [comment]
I've literally JUST rewritten the comments. This should resolve pretty much all of the bugs with comment chains, replies, the inbox duplication, and the profile comments duplication. I'll have it out for testing here in about 30 minutes to an hour. Thanks!

https://github.com/gkasdorf/memmy/pull/155

**Comment by gkasdorf** [comment]
Should be fixed in the latest update.
