### ISSUE TITLE
Image swipe to close animations

### ISSUE THREAD

**Issue by hugpeter** [gkasdorf/memmy#156]
Currently, when swiping away images, the animation abruptly ends and is a little jarring.

I'm sure you are aware and have a plan, but just wanted to put it on the issue list to keep track here. 

It would be cool if it behaved similarly to discord or Apollo where if you swipe up, the image flies up off the screen, and when you swipe down the image flies down off the screen while fading out.

**Comment by gkasdorf** [comment]
Yea I'll be working on improving those for sure. Shouldn't be too much longer.

**Comment by gkasdorf** [comment]
working on this now
