### ISSUE TITLE
Pressing image in compact view should open image viewer

### ISSUE THREAD

**Issue by enghseb** [gkasdorf/memmy#160]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I press a picture or link in compact mode and it brings me to the comments

**Describe the solution you'd like**
If it's a link, it should open the link. If it's an image, it should open in the image viewer. 

**Additional context**
It worked like this in Apollo, if that is of any assurance.

Anyway, this app is amazing and you're doing insane work. Hopefully this can be introduced one day, if not, thanks for what you're doing!

**Comment by gkasdorf** [comment]
You got me at a good time! https://github.com/gkasdorf/memmy/commit/b9fe39113d1ce804c0a0103b6e02597f1e5a5714

Releasing update in the next 30 minutes 👍
