### ISSUE TITLE
[MEM-65] [BUG] Compact view text width too small on iPad

### ISSUE THREAD

**Issue by kavbrian21** [gkasdorf/memmy#161]
**Describe the bug**
In Compact layout, post titles don’t fill all the available screen width on iPad, in either portrait or landscape orientation.

**Screenshots**

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/598394b2-934b-4571-8868-7e1e151108db/41c3f670-4135-4fed-b248-ac921ce745dd)

**Smartphone (please complete the following information):**

* Device: iPad 10 inch
* OS: 16
* Version: 72

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-65](https://linear.app/memmyapp/issue/MEM-65/[bug]-compact-view-text-width-too-small-on-ipad)</sub>

**Comment by gkasdorf** [comment]
We will do a screen dimension check to see how much space we are dealing with.

**Comment by kavbrian21** [comment]
This seems fixed in version 77. Thank you!
