### ISSUE TITLE
[Feature request] Reduce haptic intensity/add a slider

### ISSUE THREAD

**Issue by Hikiru** [gkasdorf/memmy#172]
**Is your feature request related to a problem? Please describe.**
Apollo’s haptics are very subtle, they feel good and you don’t really think about them. Memmy’s are just too much, like 5x stronger than Apollo.

**Describe the solution you'd like**
Either reduce the haptics or add a slider to change intensity.

**Comment by yrahul3910** [comment]
@gkasdorf Newbie here, do you think this would be a good first issue for me? I'd love to try it out!

**Comment by gkasdorf** [comment]
@yrahul3910 Thanks for the PR! Merged it in

@Hikiru Merged this in, you'll be able to adjust it now. Thanks for the feedback.
