### ISSUE TITLE
[MEM-70] [BUG] Memmy App has excessive caching

### ISSUE THREAD

**Issue by michikade** [gkasdorf/memmy#183]
**Describe the bug**
The app is caching an excessive amount.  For me, the app is 2.43 GB with 2.4 GB of that as Documents and Data.  

**To Reproduce**

Apple Settings -> General -> iPhone Storage -> Memmy App — the Documents & Data section is excessive, but will be different depending on use patterns

**Expected behavior**
Would it be possible to update the cache management and/or add a clear cache button to keep the app from bloating up like this?

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17 DB 2
 - Version: 0.0.1 (73)

<sub>[MEM-70](https://linear.app/memmyapp/issue/MEM-70/[bug]-memmy-app-has-excessive-caching)</sub>

**Comment by michikade** [comment]
![image](https://github.com/gkasdorf/memmy/assets/6156381/1739359b-6245-4fa7-80a7-c58667fa9a45)

**Comment by gkasdorf** [comment]
Thanks. I have some ideas on how to mitigate this. Sorry about being a hog...

**Comment by gkasdorf** [comment]
It looks like this might be related to iOS 17. I'll keep an eye on it and see what needs to be done to fix it.

In the meantime, I've added a clear cache button to the debug section in settings.
