### ISSUE TITLE
[MEM-72] Clicking on usernames on dashboard opens my own profile instead

### ISSUE THREAD

**Issue by ToughPapaya** [gkasdorf/memmy#184]
**Describe the bug**
When I'm in dashboard view and click on the username of the author of a post, it loads my own profile instead.

**To Reproduce**
1. Log into app
2. Click on the username of an author of a post

**Expected behavior**
Load the profile of the author of the post

**Smartphone (please complete the following information):**
 - Device: iPhone SE 3
 - OS: 16.5.1
 - Version 0.0.1 (73)

<sub>[MEM-72](https://linear.app/memmyapp/issue/MEM-72/clicking-on-usernames-on-dashboard-opens-my-own-profile-instead)</sub>

**Comment by gkasdorf** [comment]
Fixed and complete. Will be in next build.
