### ISSUE TITLE
[BUG] change to haptic feedback doesn’t stick

### ISSUE THREAD

**Issue by ex-youth** [gkasdorf/memmy#187]
**Describe the bug**
When changing haptic feedback from medium to either light or heavy, no change is recorded. There is no noticeable change in the haptic response. 

**To Reproduce**
1. Go to settings
2. Click on haptic response 

**Expected behavior**
Should register new setting. 

https://github.com/gkasdorf/memmy/assets/137928675/97b08321-825d-4b88-ac51-5dc1bc8349a9

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - iOS15.5.1

**Comment by yrahul3910** [comment]
Whoops--this was my bad! Minor typo caused this. Submitting a PR now.
