### ISSUE TITLE
[MEM-76] [BUG] Cannot mark replies as read

### ISSUE THREAD

**Issue by graham-pyett** [gkasdorf/memmy#188]
**Describe the bug**
When viewing your inbox, there's an envelope icon button that I assume is supposed to mark messages as read. Tapping that does nothing

**To Reproduce**

1. Recieve a reply
2. Click on 'inbox'
3. Tap envelope icon on the reply
4. See that nothing happens

**Expected behavior**
The reply should be marked as read, and the notification count should decrease by 1

**Screenshots**

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/7ab512d4-df94-4f78-8e20-106a68c80e74/2ffb7d6e-c572-4746-8798-472e1decf0d0)

**Smartphone (please complete the following information):**

* Device: iPhone \[11 pro max\]
* OS: \[e.g. iOS 16.5\]
* Version \[e.g. 0.0.1 (73)\]

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-76](https://linear.app/memmyapp/issue/MEM-76/[bug]-cannot-mark-replies-as-read)</sub>

**Comment by ann0see** [comment]
Can confirm. It used to work in the past

**Comment by gkasdorf** [comment]
I know about this. Working on making it better today.

**Comment by gkasdorf** [comment]
Complete.
