### ISSUE TITLE
Customizable slide gesture actions

### ISSUE THREAD

**Issue by RedstoneGithub** [gkasdorf/memmy#203]
**Is your feature request related to a problem? Please describe.**
no just a feature from Apollo I would like

**Describe the solution you'd like**
When you swipe a post, instead of the predefined options like upvote, downvote and reply, add customizable ones like save, and be able to change the order of gestures like apollo

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by sgriff96** [comment]
This is something we'd maybe like to add in the future but not any time soon, sorry!
