### ISSUE TITLE
[BUG] App crash on list option select

### ISSUE THREAD

**Issue by simonemike95** [gkasdorf/memmy#21]
**Describe the bug**
App crashes when choosing default list type.

**To Reproduce**
1. Tap top right "..." button to open list options
2. Choose any option.

**Expected behavior**
List option changes to selected.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.4
 - Version: 15

**Comment by gkasdorf** [comment]
Yea I literally just noticed this after pushing the update. Think I hit undo before committing the change...give me a moment.

**Comment by simonemike95** [comment]
No worries, just wanted to help out reporting anything I find. I realize you just put the testflight release up mere hours ago, so I expected to run into some bugs.

**Comment by gkasdorf** [comment]
Fixed, will be on TF in a few.
