### ISSUE TITLE
[MEM-109] Compact view post thumbnail previews for websites don't show for majority of posts

### ISSUE THREAD

**Issue by joeromsa** [gkasdorf/memmy#210]
**Is your feature request related to a problem? Please describe.**
For posts that are website links, I find that most of the thumbnail previews don't display an image. Apollo for example has preview images for websites, twitter, YouTube, etc.

**Describe the solution you'd like**
Display the preview image for all posts if possible. Not essential but I find it makes scrolling through the feed more enjoyable. 

**Additional context**
On version 0.0.1 (75)
![IMG_1764](https://github.com/gkasdorf/memmy/assets/47951551/b64c14aa-992a-4a69-a00b-8b00c80f8d8e)

<sub>[MEM-109](https://linear.app/memmyapp/issue/MEM-109/compact-view-post-thumbnail-previews-for-websites-dont-show-for)</sub>

**Comment by gkasdorf** [comment]
Hmm they seem to load alright for me from my testing (although I found another bug to fix in the process of this!) Is this still happening? It's possible it was a network issue at the time you were trying to load them.

**Comment by joeromsa** [comment]
Yay! But yeah, I'm still not really seeing website previews. Regular image previews show up fine though. I tried reinstalling the app and still not really getting them. If I scroll back to older posts from 2 days ago some of them start to have the previews, but none of the newer posts do
![Screenshot 2023-06-28 at 4 44 42 PM](https://github.com/gkasdorf/memmy/assets/47951551/8cfdb3d8-8344-479c-922c-1a400ce54008)
.

**Comment by gkasdorf** [comment]
Real weird. I'll check out that community later and see if I am having the same issue. Also, I'll fix that color issue on the light theme (can't see the link, opacity is no good.

Thanks!

**Comment by sgriff96** [comment]
I'm also not able to reproduce this, I've noticed sometimes websites don't have a preview image that we get from the API, but not seeing it as consistently as you seem to be.
