### ISSUE TITLE
[MEM-110] Use UIKeyboardType.URL in server address field

### ISSUE THREAD

**Issue by lukelbro** [gkasdorf/memmy#211]
**Is your feature request related to a problem? Please describe.**
When on the adding account screen the `SERVER ADDRESS` field should use the url type keyboard.

**Describe the solution you'd like**
Use `UIKeyboardType.URL`
https://developer.apple.com/documentation/uikit/uikeyboardtype/url

**Describe alternatives you've considered**
The pain of pressing the 123 keyboard button and then pressing . and then press the ABC keyboard button.

**Additional context**
Obviously not a show stopper but very easy fix. Thanks for your hard work.

<sub>[MEM-110](https://linear.app/memmyapp/issue/MEM-110/use-uikeyboardtypeurl-in-server-address-field)</sub>

**Comment by gkasdorf** [comment]
I'll fix this in the next update along with adding the @ symbol to the keyboard for search.

**Comment by gkasdorf** [comment]
This will be in the next update.
