### ISSUE TITLE
[MEM-112] [BUG] Subscriptions not loading, took about 10 minutes or so of forcedly closing the app to get it back

### ISSUE THREAD

**Issue by sc0ttwood** [gkasdorf/memmy#213]
![IMG_1429](https://github.com/gkasdorf/memmy/assets/138073160/d5bca89a-62cb-4b31-b6a5-7bc4e63490e7)

And I don't know what caused it as on the site it was working fine.

<sub>[MEM-112](https://linear.app/memmyapp/issue/MEM-112/[bug]-subscriptions-not-loading-took-about-10-minutes-or-so-of)</sub>

**Comment by gkasdorf** [comment]
This is a server error, but I am going to implement something now to handle this better and allow the user to refresh.

**Comment by gkasdorf** [comment]
No longer an issue. I have reworked this screen.
