### ISSUE TITLE
[BUG] Block Community is Crashing, important.

### ISSUE THREAD

**Issue by sc0ttwood** [gkasdorf/memmy#214]
I like to keep my home clean, and to do that I need to block communities and I have just found out that I can not do it as it crashes the app, emergency bug here.

*Can't attach video*

@ me on discord to get the video.

**Comment by gkasdorf** [comment]
Think we have the fix for this figured out. Was a mix of issues, same issue causing subscribe crash. We'll have an update out soon.

**Comment by gkasdorf** [comment]
We're fixing this now.

**Comment by gkasdorf** [comment]
https://github.com/gkasdorf/memmy/pull/215
