### ISSUE TITLE
Add instance name to community list in drop down

### ISSUE THREAD

**Issue by simonemike95** [gkasdorf/memmy#22]
**Is your feature request related to a problem? Please describe.**
There are often multiples of communities across different instances.

**Describe the solution you'd like**
Append instance names to communities in the drop down so it's easier to tell duplicate communities apart across instances.

**Describe alternatives you've considered**
Just clicking on them and seeing the contents of each.

**Comment by gkasdorf** [comment]
This is something I've been thinking about. I suppose there definitely are instances where you could be trying to access a community with the same name but on a different instance. I'll think of a good way to implement that. The dropdown might not be the best way to go, and I'm actually just using it right now until I add a screen for all of your subscribed communities. The dropdown would be for the favorites you select. Thanks!

**Comment by gkasdorf** [comment]
This will be in the next release. Also, the instance name is shown on the community feed screen.

**Comment by gkasdorf** [comment]
![image](https://i.imgur.com/lwkhJ5f.png)

**Comment by simonemike95** [comment]
Awesome, thanks for the work being done.
