### ISSUE TITLE
[MEM-111] [BUG] Image not rendered in main feed

### ISSUE THREAD

**Issue by dsl101** [gkasdorf/memmy#223]
**Describe the bug**
This post doesn’t show the image or link in the main feed. 

https://lemmy.world/post/793438

<img width="375" alt="image" src="https://github.com/gkasdorf/memmy/assets/900542/5cc81528-ea11-47ff-8ddd-0ecf0225e82e">

it’s a bit better in the post, but ideally would just be the image. 

<img width="375" alt="image" src="https://github.com/gkasdorf/memmy/assets/900542/6878e6f4-5492-438a-af28-306c56314846">

Or is it just a broken post?

<sub>[MEM-111](https://linear.app/memmyapp/issue/MEM-111/[bug]-image-not-rendered-in-main-feed)</sub>

**Comment by gkasdorf** [comment]
Seems to be a markdown thing, odd that that one didn't get rendered though since the markdown did not get cut off...I'll take a peek.

**Comment by dsl101** [comment]
I've seen it a handful of times now. Let me know if other examples are useful, and I'll try to link them if so.

**Comment by sgriff96** [comment]
Isn't this because I changed it to use <Text> instead of markdown for previews @gkasdorf?

**Comment by gkasdorf** [comment]
@sgriff96 Oh yea it might be. The `RenderMarkdown` component takes the text and checks for the images. If you want, we could just keep the text rather than RenderMarkdown but use that same function before we do so.

**Comment by sgriff96** [comment]
@gkasdorf that'd probably be good, we should just strip out any markdown images imo. Only show text in preview.

**Comment by gkasdorf** [comment]
@sgriff96 Looking closely this is one of those weird things too where instead of just posting the image link as the post URL, they for whatever reason put it - and only it - inside the body. I guess we *could* check for that but I think it's way too rare of an occurrence to be something major.

But we probably also don't want to just not show anything there do we? I don't know. Whichever way we want to go about it, we can use [findImages()](https://github.com/gkasdorf/memmy/blob/157ecde242f9b048ff55a99937c84f0f1bc6ffaa/helpers/MarkdownHelper.ts#L2). Returns both the cleaned up text and an array of the images.

**Comment by dsl101** [comment]
Just to chime in, I’ve seen this 3 times now. Not sure if it’s a ‘thing’
from another platform, or how some things get shared etc. It would be great
if it went away, and greater it Memmy could just deal with it :)

**Comment by sgriff96** [comment]
> @sgriff96 Looking closely this is one of those weird things too where instead of just posting the image link as the post URL, they for whatever reason put it - and only it - inside the body. I guess we _could_ check for that but I think it's way too rare of an occurrence to be something major.
> 
> But we probably also don't want to just not show anything there do we? I don't know. Whichever way we want to go about it, we can use [findImages()](https://github.com/gkasdorf/memmy/blob/157ecde242f9b048ff55a99937c84f0f1bc6ffaa/helpers/MarkdownHelper.ts#L2). Returns both the cleaned up text and an array of the images.

Hmm yea so there are two types of occurrences that could mess us up atm that I can think of:
1. A user posts a markdown link of just an image - we can detect this and convert it to how we render an image post
2. A user posts text with a markdown link. I think here we should strip out the link from the preview, and just show text.

Am i missing any other cases?

**Comment by gkasdorf** [comment]
That seems right. If there is text we should just show that, and if there is just an image (which really doesn't make sense but...obviously it's happening) we should render the image as we normally would if it was the post URL.
