### ISSUE TITLE
[MEM-116] [BUG] NSFW toggle appears twice in settings

### ISSUE THREAD

**Issue by ex-youth** [gkasdorf/memmy#224]
**Describe the bug**
NSFW toggle appears twice in settings, first immediately below “account” and then again below “haptics.” 

**To Reproduce**
1. Go to settings
2. Scroll down to Haptics
3. See duplicate toggle

**Expected behavior**
Should only be one set of toggles. 

**Screenshots**

<sub>[MEM-116](https://linear.app/memmyapp/issue/MEM-116/[bug]-nsfw-toggle-appears-twice-in-settings)</sub>

**Comment by gkasdorf** [comment]
Fixed.
