### ISSUE TITLE
[MEM-117] [BUG] Only first image is shown in multiple image post

### ISSUE THREAD

**Issue by JeremyLeland** [gkasdorf/memmy#227]
**Describe the bug**
Memmy only shows first image in attached post with 5 images. There is no obvious way to see the remaining images from Memmy. The post text is also missing. 

**To Reproduce**
1. Go to https://lemmy.world/post/768129

**Expected behavior**
Should be able to see multiple images (post has 5 in web browser). Should also see post text: “Here are some proposed graphics.”

**Screenshots**
![Only first image](https://github.com/gkasdorf/memmy/assets/50390633/c4951b2f-aae4-4daa-a606-bf045b4f3f5f)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 16.5.1
 - Version 0.0.1 (77)

<sub>[MEM-117](https://linear.app/memmyapp/issue/MEM-117/[bug]-only-first-image-is-shown-in-multiple-image-post)</sub>

**Comment by z01L** [comment]
I’m also experiencing this one. [Here’s ](https://infosec.pub/post/277536) an example where you have an image and post text. Memmy doesn’t display the post text at all so it can make things a bit confusing when reading.

**Comment by sgriff96** [comment]
Thanks will look into both issues tonight

**Comment by JeremyLeland** [comment]
Possibly related to #229

**Comment by gkasdorf** [comment]
Fix merged.

**Comment by JeremyLeland** [comment]
The post text is visible now, but there is still no way to view the other 4 images in the post (https://lemmy.world/post/768129). Should I open a separate bug? (Doesn’t look like I can deactivate this one)

**Comment by sgriff96** [comment]
Sorry this was incorrectly closed, working on this tonight

**Comment by Taxxor90** [comment]
Not exactly related to the missing images but since the issue of additional text not showing was also mentioned here and that linked issue is closed:

I still am missing text in many posts that either have a link or an image inside them 

Here is how it looks on Memmy 
![image](https://github.com/gkasdorf/memmy/assets/45570250/8f9e9dfa-864e-4bc1-9115-e7f630bb349d)

And this is on MLem
![image](https://github.com/gkasdorf/memmy/assets/45570250/e6b1c156-52a8-420b-b0c1-b09010bf3ab4)

**Comment by gkasdorf** [comment]
@Taxxor90 Ok cool, I see the issue. We'll get it fixed.

**Comment by sgriff96** [comment]
Closed, main issue should be resolved in #305, we aren't going to embed images like that unfortunately @Taxxor90
