### ISSUE TITLE
[MEM-118] Convert the feed's ellipsis icon button to a more dynamic icon button

### ISSUE THREAD

**Issue by jacksonopp** [gkasdorf/memmy#228]
**Is your feature request related to a problem? Please describe.**
It is unclear which kind of feed I am looking at (instance, all, subscribed). Clicking the ellipsis icon does not indicate which one is selected (with a checkmark or similar). It's also a little unclear what clicking that button does, other than open *some* menu.

**Describe the solution you'd like**
We could convert the ellipsis icon button to one similar to the feed filter button (hot, active, etc) which contains some more meaningful icons than the three ellipsis.

**Describe alternatives you've considered**
- Next to the instance name below the username, we could have in text what kind of feed we're looking at.
- In the menu that pops up when you click the ellipsis icon button, we could add a checkmark indicating which one is currently selected

**Additional context**
These are some low-fi mockups containing icons we might want to consider.
![iPhone 14 - All](https://github.com/gkasdorf/memmy/assets/50721527/072bcade-17d9-46f2-afba-7b3115f1c9c6)
![iPhone 14 - Instance](https://github.com/gkasdorf/memmy/assets/50721527/f2f6206b-473e-487e-b0ab-fd044d98f18c)
![iPhone 14 - Subscribed](https://github.com/gkasdorf/memmy/assets/50721527/5ddc01f5-4088-48e5-8db0-f33d1f7c6769)

<sub>[MEM-118](https://linear.app/memmyapp/issue/MEM-118/convert-the-feeds-ellipsis-icon-button-to-a-more-dynamic-icon-button)</sub>

**Comment by sgriff96** [comment]
This is something I've been meaning to do, but if you want to give it a go we'd greatly appreciate it!

**Comment by jacksonopp** [comment]
I'll take a stab at it! Might need some help getting expo up and running correctly, but I'll join the discord and ask there if I need any help

**Comment by gkasdorf** [comment]
@jacksonopp Hop in whenever! I've actually converted things over to use a bare workflow, so it should be a bit easier to build now. I think a simple `npx pod install` and `yarn ios` will handle it now for you.

We'll be around though if you need help!

**Comment by jacksonopp** [comment]
Closed via #255
