### ISSUE TITLE
[MEM-120] [BUG] Post Body Copy Not Shown for Link and Photo Posts

### ISSUE THREAD

**Issue by lucible** [gkasdorf/memmy#229]
**Describe the bug**
Post copy is not shown for photo and link posts.

**To Reproduce**
1. Tao into any link or photo post that has post body copy
2. Notice the lack of content

**Expected behavior**
Link and photo body copy should be present and readable when I tap into a post.

**Screenshots**
Post on web UI with lots of interesting body content:
![image](https://github.com/gkasdorf/memmy/assets/45129600/2898749b-4113-4c87-a4f4-38f30ff5e93c)

Post on Memmy missing all the body content:
![image](https://github.com/gkasdorf/memmy/assets/45129600/fea5077c-38ff-47df-af9f-a44c07d3ab45)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: 15
 - Version 77

**Additional context**
This makes the Memmy experience much worse than the web UI. I had almost switched my usage entirely to Memmy but then noticed this issue and am now back to using the web UI. Having post body copy is super important! I want to read the stories and info people share about their images and to be able to comment on it.

<sub>[MEM-120](https://linear.app/memmyapp/issue/MEM-120/[bug]-post-body-copy-not-shown-for-link-and-photo-posts)</sub>

**Comment by sgriff96** [comment]
Thanks for pointing this out, I'll look into it tonight, hopefully can push out a fix

**Comment by gkasdorf** [comment]
Fix merged.
