### ISSUE TITLE
[BUG] Feed does not match sort + listing type

### ISSUE THREAD

**Issue by lucible** [gkasdorf/memmy#24]
**Describe the bug**
When listing type is set to subscribed and the feed is refreshed, posts from communities I'm not subscribed to still appear in the feed. 

**To Reproduce**
1. Go to Settings
2. Set Default Listing Type to Subscribed
3. Go to Feed
4. Pull down to refresh; unsubscribed posts visible in feed

**Expected behavior**
Should only see subscribed posts when default listing type is set to subscribed

**Screenshots**

https://github.com/gkasdorf/memmy/assets/45129600/c8d929e0-5018-4aab-bf33-288f11ab6f16

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: 15.7
 - Version 16

**Comment by gkasdorf** [comment]
That setting is just the default, it will use that default whenever you open the app. To change while you're looking at the feed, you can use the left most button on the right.
