### ISSUE TITLE
Default feed settings not working

### ISSUE THREAD

**Issue by ToughPapaya** [gkasdorf/memmy#250]
**Describe the bug**
My feed is not following my default listing settings. I'm getting posts that I'm not subscribed to even though my default listing type is subscribed.

**To Reproduce**
1. Change default sort to new and default listing type to subscribed.
2. Refresh feed.

**Expected behavior**
The feed should list posts that are new in the communities I'm subscribed to.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 3
 - OS: 16.5.1
 - Version: 0.0.1 [77]

**Comment by gkasdorf** [comment]
The default setting is for app launch. You can select the sort of the current session from the icon at the top. 

It might be worth updating this automatically though once a user changes the setting, I’ll add this to the list.

**Comment by ToughPapaya** [comment]
I cannot select subscribed from the top of the current session. The only options are:

- Top Day
- Top Week
- Hot
- Active
- New
- Most Comments

**Comment by ToughPapaya** [comment]
There should be text stating that the user should restart the app when default listing settings are changed.

**Comment by sgriff96** [comment]
No app needs restarting, you just need to change it in the top right of the feed. Because you had that selected, the default setting doesn't overwrite what current feed filter selection nor should it.
