### ISSUE TITLE
Memmy's nose looks like a badge notification

### ISSUE THREAD

**Issue by jderose9** [gkasdorf/memmy#254]
I realize this may be a little trivial or a personal problem, but I keep seeing the memmy icon in the peripheral and think the red circle with white content is a badge indicator on iOS. Probably long term the solution would be to allow for configurable icons but thought I would mention it in case others are having this problem.

**Comment by b-bayport** [comment]
I don't have a problem with this but I did think the same that the nose looks like a notification indicator. 

Overall personally I don't like the icon, but that is in no way an issue for me.  
Should this be moved to a discussion rather than a GitHub-Issue?

**Comment by sgriff96** [comment]
Correct, not a relevant github issue. FWIW we are looking at hiring a professional designer for the official app icon.

**Comment by jderose9** [comment]
Just to be clear, I DO consider this an accessibility issue, not a "i don't prefer this" type of discussion. I wasn't making a judgement on the creative aspect of the icon.
