### ISSUE TITLE
Can not implement images into posts.

### ISSUE THREAD

**Issue by sc0ttwood** [gkasdorf/memmy#260]
As I was writing up a new post I realised I couldn't implement pictures, it just closes the keyboard.

https://cdn.discordapp.com/attachments/1121198702451773494/1124403806160031895/RPReplay_Final1688149116.mov

**Comment by b-bayport** [comment]
What version are you using?
The screens in your video don't look like mine on my iPhone

**Comment by sgriff96** [comment]
I can't view that video it won't show up for me

**Comment by gkasdorf** [comment]
This is resolved.
