### ISSUE TITLE
Tapping the italic or bold option when writing a post closes the iOS keyboard

### ISSUE THREAD

**Issue by minorsecond** [gkasdorf/memmy#264]
**Describe the bug**
At least when creating a new post, tapping the italic or bold option causes the keyboard to close. 

**To Reproduce**
1. Start writing a new post
2. Tap on italic or bold
3. See the keyboard close

**Expected behavior**
This shouldn’t happen 

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Version 0.0.2 (5)

**Comment by minorsecond** [comment]
This actually happens with any of those buttons.

**Comment by gkasdorf** [comment]
On it.

**Comment by gkasdorf** [comment]
Fixed.
