### ISSUE TITLE
Add support for bigger screens/ipad

### ISSUE THREAD

**Issue by Letsu** [gkasdorf/memmy#27]
**Is your feature request related to a problem? Please describe.**
Only optimized for iphones.  No support for ipad

**Describe the solution you'd like**
Add support for bigger screens. 

**Additional context**
When the app gets opened on a screen bigger then a iphone, the view is only a part of the screen.

**Comment by gkasdorf** [comment]
I'll do some testing with a simulator and see what I can do to make it look nice. Don't have an iPad handy.

I'm guessing the big issue is images?

**Comment by gkasdorf** [comment]
Oh, I get it. Probably don't have iPad support enabled. Let me do that and see how it works. If it looks at least functional right now I'll push it in the next update.

**Comment by phriedrich** [comment]
Works great now on the iPad. 👍

**Comment by Letsu** [comment]
Can also confirm
