### ISSUE TITLE
[BUG] Comment chains too long/deep position gets funky

### ISSUE THREAD

**Issue by simonemike95** [gkasdorf/memmy#28]
**Describe the bug**
When a comment chain is more than 5 comments deep, the horizontal position of the 6th comment is incorrect.

**To Reproduce**
See/create any comment chain more than 5 comments deep.

**Expected behavior**
After the 5th comment, maybe do as Apollo did and have a “continue reading comments…” button that expands the comment chain from the last comment before the button to full screen with 4 more comments (and another “continue…” button).

**Screenshots**
![IMG_2380](https://github.com/gkasdorf/memmy/assets/19980344/64ad9d69-d219-4903-847d-235ebb9241e3)
![IMG_2381](https://github.com/gkasdorf/memmy/assets/19980344/30f6cc4e-883f-4e9d-a65e-fcde0a3583c0)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16.4
 - Version: 16

**Comment by gkasdorf** [comment]
Noticed this earlier too. Going to work on a comment-chain screen for longer chains, since it will get pretty ugly for the comments to keep getting smaller and smaller.

**Comment by gkasdorf** [comment]
This is fixed.
