### ISSUE TITLE
Settings: Default Sort hot

### ISSUE THREAD

**Issue by bviefhues** [gkasdorf/memmy#289]
On the settings page, selecting default sort "hot" shows "MostCommented"

Memmy 0.0.2 (6)

**Comment by bviefhues** [comment]
Screenshot attached. 

![image](https://github.com/gkasdorf/memmy/assets/1117300/d92bff59-c6d9-4b13-9461-c7bb5b331806)

**Comment by yrahul3910** [comment]
I feel like this is simple enough that I can do it. @gkasdorf There seems to be a related bug (not sure if it's reported): should [this line](https://github.com/gkasdorf/memmy/blob/main/components/screens/settings/SettingsIndexScreen.tsx#L220) instead have `index === 5`?

**Comment by gkasdorf** [comment]
Oh yeah, that is the one. I think it was reported. Go ahead and update that as well. Thanks.

**Comment by sgriff96** [comment]
I thought I changed those options to instead be a map, then we didn't have to worry about index. Do you remember me talking about that? @gkasdorf

**Comment by gkasdorf** [comment]
@sgriff96 Yea I do. Seems like we are not using that here though in SettingsIndexScreen

```
            onPress={() => {
              const options = [
                "Top Day",
                "Top Week",
                "Hot",
                "Active",
                "New",
                "Most Comments",
                "Cancel",
              ];
              const cancelButtonIndex = 6;

              showActionSheetWithOptions(
                {
                  options,
                  cancelButtonIndex,
                  userInterfaceStyle: theme.config.initialColorMode,
                },
                (index: number) => {
                  if (index === cancelButtonIndex) return;

                  let selection;

                  if (index === 0) {
                    selection = "TopDay";
                  } else if (index === 1) {
                    selection = "TopWeek";
                  } else if (index === 4) {
                    selection = "MostComments";
                  } else {
                    selection = options[index];
                  }

                  dispatch(setSetting({ defaultSort: selection }));
                }
              );
            }}
```

Should we be using `sortOptions` from `FeedSortButton.tsx`? If so might want to move that to `types` and use it in both places.

**Comment by yrahul3910** [comment]
That might be a good idea. As-is, I'm adding a function like this to `SettingsIndexPage`:
```ts
const getDefaultSortText = (sortType: SortType): string => {
    switch (sortType) {
      case "TopDay":
        return "Top Day";
      case "TopWeek":
        return "Top Week";
      case "MostComments":
        return "Most Comments";
      default:
        return sortType;
    }
  };
```

With your proposed method, I could instead do something along the lines of
```ts
const getDefaultSortText = (sortType: SortType): string => {
    const index = sortOptions.map(x => x[0]).indexOf(sortType);
    return sortOptions[index][1]; 
  };
```

Of course, the true win would be fixing the DRY principle violation.
