### ISSUE TITLE
[BUG] Duplicates of posts when scrolling

### ISSUE THREAD

**Issue by gkasdorf** [gkasdorf/memmy#29]
Can I get some feedback from you guys on this. It seems that sometimes whenever scrolling down the page, after the first 20 posts you will see many of the same posts come up again when loading.

I've made sure that the requests are going through correctly to Lemmy for offsetting already pulled posts, so I'm thinking it is something to do with the Lemmy API. I'll investigate this more, but wanted to hear what you guys are seeing.

Oddly enough, I don't see this on a simulator, but that also might be because I'm not actually taking my time viewing the content. I've noticed that if you just refresh the page that the content will update and be quite different, so I'm thinking that the same results are just ending up in a different place in the API response.

I'll probably add some logic to avoid adding duplicate posts to the view after they are retrieved.

**Comment by lucible** [comment]
I've encountered this issue after refreshing my feed before. It might be associated with hitting the bottom of the feed quickly? I was browsing without having pulled down from the top to refresh and didn't run into the issue, then I just got it to trigger twice by pulling from the top to refresh and scrolling far enough down that I get a loading indicator. After the loading indicator, the same batch of posts appears. 

I'm also seeing posts move around / not be sorted in a consistent order, and they don't seem to match the order in my settings (New).

**Comment by gkasdorf** [comment]
> I've encountered this issue after refreshing my feed before. It might be associated with hitting the bottom of the feed quickly? I was browsing without having pulled down from the top to refresh and didn't run into the issue, then I just got it to trigger twice by pulling from the top to refresh and scrolling far enough down that I get a loading indicator. After the loading indicator, the same batch of posts appears.
> 
> I'm also seeing posts move around / not be sorted in a consistent order, and they don't seem to match the order in my settings (New).

Actually, I just noticed something that might be causing it. Let me see if that's the issue.

**Comment by z01L** [comment]
Yes I’m also experiencing the same after scrolling for a while. Mlem also has the same [issues](https://lemmy.world/post/100168)  so you might be right that it’s an issue with the API.

**Comment by gkasdorf** [comment]
So part of the problem was on me, but there are still some duplicates. I'll add some logic to prevent that.

**Comment by gkasdorf** [comment]
Added the logic. Right now, I only check against the first 50 posts that got pulled, since that seems to be the biggest issue. Don't think there's a huge need to check the rest of them.

**Comment by gkasdorf** [comment]
Should be good to go...Will keep watching for these issues.
