### ISSUE TITLE
Error submitting vote

### ISSUE THREAD

**Issue by sh4d0wph03n1x** [gkasdorf/memmy#292]
**Describe the bug**
Whenever trying to upvote or downvote, get the error "error submitting vote."

**To Reproduce**
1. Upvote post
2. ???
3. Profit?

**Expected behavior**
Memmy properly upvotes post 

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/26177794/9f063cf6-cb27-4c5c-844e-b9fa3aba24fc)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.1.2
 - Version 0.02

**Additional context**
Already verified account and etc

**Comment by gkasdorf** [comment]
The error is the result of a server issue. If we are unable to complete the request to upvote your comment then you receive this error. Sometimes, the request might actually go through and if you refresh you'll see the new upvote, but the API is returning something else to us (or not returning anything at all usually), so we let you know there was an error.

I see you're using Lemmy.world which is going through some massive pains right now, so this is almost certainly the issue. I experience it frequently on lemmy.ml as well.

**Comment by sh4d0wph03n1x** [comment]
Understood, thanks!
