### ISSUE TITLE
Fedia.io not working for login

### ISSUE THREAD

**Issue by alberthdev** [gkasdorf/memmy#301]
**Describe the bug**
Fedia.io not working for logging in. Getting this pop up when trying to log in:

"Unknown error occurred. Here is more info: SyntaxError: JSON Parse error:
Unexpected token: <"

**To Reproduce**
1. Skip tutorial and go to "I have an account"
2. Click on "Login"
3. Enter "fedia.io" for the server and a valid username and password
4. See above error

**Expected behavior**
Logged in successfully and seeing subscribed content.

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/1274384/f0186a5b-bd81-4d5c-b5e8-fa8775b958a5)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 16.4.1(a)
 - Version 0.0.2 (6)

**Logs:**

Mo logs obtainable due to being stuck in login stage.

**Additional context**
N/A

**Comment by z01L** [comment]
The kbin API hasn’t been enabled yet so Fedia.io won’t work.
