### ISSUE TITLE
Error language not allowed. 

### ISSUE THREAD

**Issue by adude007** [gkasdorf/memmy#325]
![IMG_0948](https://github.com/gkasdorf/memmy/assets/73857010/5cf8b60e-968b-4ac0-86c7-5f81be91e02d)

**Describe the bug**
Can not reply to post comments

**To Reproduce**

**Expected behavior**
Comment to post 

**Screenshots**
See above

**Smartphone (please complete the following information):**
 - Device: iPhone 14pro
 - OS: 17.0 B2
 

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 Will send with subject line referencing this report

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by adude007** [comment]
Cannot send debug logs. Nothing happens when taping version number or the email debug logs button.

**Comment by gkasdorf** [comment]
Have you updated to 0.0.2.7?

**Comment by gkasdorf** [comment]
Nevermind...https://github.com/gkasdorf/memmy/issues/306

**Comment by adude007** [comment]
> Have you updated to 0.0.2.7?

Yes I have. My test flight is auto updating for me. Noticed its dupe issue.
