### ISSUE TITLE
Tapping a link to a user profile gives an error

### ISSUE THREAD

**Issue by minorsecond** [gkasdorf/memmy#326]
**Describe the bug**
Tapping a link to a user profile throws an error. 

**To Reproduce**
1. Go to this post: https://lemmy.dbzer0.com/post/327341
2. Tap on the second hyperlink
3. See error

**Expected behavior**
Tapping profile links in post or comment text should successfully open that profile

**Screenshots**
![IMG_0777](https://github.com/gkasdorf/memmy/assets/2933789/5f8570e9-547f-4532-8a4c-1ee00887e92e)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.5.1
 - Version 0.0.2 (7)

**Comment by minorsecond** [comment]
It appears that this link may be invalid, so maybe a more descriptive error message in this case would work.

**Comment by gkasdorf** [comment]
Yea, we have something on the roadmap to deal with error handling much better. I have not seen that particular one though, it shouldn't have given you an error like that. I'll look into it.
