### ISSUE TITLE
Set app type to “Social”

### ISSUE THREAD

**Issue by minorsecond** [gkasdorf/memmy#328]
**Is your feature request related to a problem? Please describe.**
For those trying to watch social media usage, it would be nice if Lemmy showed up as Social in the screen usage pane in iOS settings. 

**Describe the solution you'd like**
Change the app type from other to social. Perhaps other is the default and this hasn’t been set yet. 

**Additional context**
![IMG_0778](https://github.com/gkasdorf/memmy/assets/2933789/fc677ae0-dfd5-4468-852f-df305ee76a50)

**Comment by gkasdorf** [comment]
As far as I know, this is because it has not been reviewed by Apple yet and as such doesn't actually have a tag yet. Once that happens, it should start showing as social 👍
