### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mars7x** [gkasdorf/memmy#34]
**Describe the bug**
The iOS keyboard and some other UI elements use light mode even with dark mode enabled.

**To Reproduce**
1. Enable dark mode
2. Start typing or open the copy/paste dialogue.

**Expected behavior**
Use dark mode on the UI if you have it enabled.

**Screenshots**

![image](https://github.com/gkasdorf/memmy/assets/112448675/17cb1f89-6778-4a4d-92b2-3abfb371add5)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 16.5
 - Version 0.0.1

**Comment by gkasdorf** [comment]
Oversight on my part. I'll fix it and get it updated. Thanks!

**Comment by gkasdorf** [comment]
Fixed. Will be included in tonights release.

**Comment by Mars7x** [comment]
Hey, just thought I'd let you know that the copy and paste pop up thing still has this issue. 

![image](https://github.com/gkasdorf/memmy/assets/112448675/9834bd4e-6fb3-47e6-8620-fe33876f46dc)
