### ISSUE TITLE
[BUG] Unable to Upvote/Downvote posts after viewing posts

### ISSUE THREAD

**Issue by z01L** [gkasdorf/memmy#36]
**Describe the bug**
When you scroll through the main feed, you can upvote/downvote posts. But if you view a posts and then go back and try to upvote, nothing happens.

Also when upvoting/downvoting the post, the total vote score doesn't update.

**To Reproduce**
1. Scroll through main feed
2. View a post that you haven't up/downvoted before
3. Go back to main feed
4. Try to up/downvote
5. UI doesn't register the upvote/downvote
6. Vote score on the post doesn't change

**Expected behavior**
Upvote/downvote is registered and the total vote score updates to reflect the change.

**Screenshots**
https://streamable.com/z6rnnq

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: [e.g. iOS16.5
 - Version 0.0.1(18)

**Comment by gkasdorf** [comment]
Yea, it's a state issue. I'll fix this tonight and have it in the nightly.

**Comment by b-bayport** [comment]
I'm seeing issue of counter not updating after I upvote.  
I also not able to vote on comments under a post

**Comment by gkasdorf** [comment]
Fixed.
