### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ppadovani** [gkasdorf/memmy#37]
**Describe the bug**
Can't login, cursor keeps jumping to server field

**To Reproduce**
1. Type Lemmy.world in server field
2. Try and type a username in, cursor jumps back to server field

**Expected behavior**
Either indicate what is wrong with the server field if that's the issue, or put up an error. Cursor should never jump between fields.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: latest
 

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by gkasdorf** [comment]
@ppadovani Can you please check for an update on TestFlight? I released a fix for this (at least it was fixed when I tested it 😅

**Comment by ppadovani** [comment]
Hahaha, just did and it fixed this issue. Sorry about that, close this! Looking good so far!

**Comment by gkasdorf** [comment]
> Hahaha, just did and it fixed this issue. Sorry about that, close this! Looking good so far!

No problem! I've been known to hit undo before committing so I wasn't positive it was working! 😆 Let me know if you find anything else.
