### ISSUE TITLE
[BUG] Upvoting first comment in post leads to upvotes farther down

### ISSUE THREAD

**Issue by TysonCodes** [gkasdorf/memmy#39]
If I ago to a post I’ve never seen before and scroll through the comments none are upvoted by me (green) as expected. If I then upvote the first top-level comment it increases by 1 and shows upvoted by me (green) as expected. If I then scroll down through comments I will see other top-level comments showing green (indicating I upvoted them) which is not expected. There seems to be some pattern where it repeats but I’m unsure exactly what it is. 

Perhaps some ID is being reused and coupling comment statuses?

Using 0.0.1(19)

Thanks!

**Comment by gkasdorf** [comment]
This is a state issue related to my change in using FlashList over FlatList. Need to actually store the upvote in the comments state rather than just changing the UI. Thanks for letting me know!

**Comment by gkasdorf** [comment]
Sorry for taking a while, but this should be mostly fixed. If you keep running into it feel free to reopen this issue.
