### ISSUE TITLE
User Onboarding

### ISSUE THREAD

**Issue by gkasdorf** [gkasdorf/memmy#4]
In an attempt to make user registration as easy as possible, a user onboarding process will be used.

 - Have a list of available instances to register with. Should a specific instance be pre-selected with the option to change? If so, how should we select which instance is pre-selected?
 - Information about how things work should be provided during onboarding. Similar to the onboarding screen that Mastodon uses, but with better information (Mastodon's is a bit difficult to understand)
 - Perhaps we can use [this guide from Lemmy.world](https://lemmy.world/post/37906) as some content to provide to users.

**Comment by gkasdorf** [comment]
A sample of the forms that should be provided to users for registration. For server, there should be some way of supplying information about the available instances and information about that particular instance (similar to join-lemmy.org). While a dropdown by itself would work, this wouldn't offer any details about that particular instance.

![Screenshot 2023-06-12 at 4 34 39 PM](https://github.com/gkasdorf/memmy/assets/127079571/0ef1c2e0-4b60-4cc3-b18a-a066e740d096)
![Screenshot 2023-06-12 at 4 34 32 PM](https://github.com/gkasdorf/memmy/assets/127079571/cd6fcc28-7836-4240-9854-cb4166f160bc)

Should a default instance be selected? How should that instance be selected?

**Comment by Memphius** [comment]
Give people some basic explanation to accommodate registration and/or login. A preselection of top 10 servers would be nice to smoothen the process of onboarding.

As far as detailed instructions I'd recommend those on Lemmy.world as well. That's how I got myself some lemmytime.

Sidequestion, do you prefer app feedback within TestFlight or as issues on git?

**Comment by gkasdorf** [comment]
> Give people some basic explanation to accommodate registration and/or login. A preselection of top 10 servers would be nice to smoothen the process of onboarding.
> 
> As far as detailed instructions I'd recommend those on Lemmy.world as well. That's how I got myself some lemmytime.
> 
> Sidequestion, do you prefer app feedback within TestFlight or as issues on git?

Either one works, but a bit easier to track on GitHub and better communication. You can't follow up with a reporter on TestFlight.

**Comment by ajkenny84** [comment]
I can't remember which fediverse app it was, but when signing into the app it offered pre-configured buttons for the most popular servers so all I had to do was click my instance name instead of typing it out

of course this would require you to find/store a list of instances, but it would facilitate an easier log-in experience

for new signups, perhaps you could parse out the instances from this site and offer one based on location/language/popularity?

https://lemmy.fediverse.observer/list

**Comment by gkasdorf** [comment]
> I can't remember which fediverse app it was, but when signing into the app it offered pre-configured buttons for the most popular servers so all I had to do was click my instance name instead of typing it out
> 
> of course this would require you to find/store a list of instances, but it would facilitate an easier log-in experience
> 
> for new signups, perhaps you could parse out the instances from this site and offer one based on location/language/popularity?
> 
> https://lemmy.fediverse.observer/list

That looks neat, was actually thinking about asking for something like that. Looks like we can get the info from [right here](https://lemmy.fediverse.observer/app/views/tabledata.php?software=lemmy). I'll probably cache it somewhere and update every hour or so to be nice to the site owner. Thanks for the link!

**Comment by Genfood** [comment]
Ask users in the beginn questions about, their preferences. Political views, NSFW and other important things (moderating, federation,...). And out of the answers suggest an instance or multiple.

This could make it easy for newer users, and for those who know what they are doing, give them the expert mode. 🤝

**Comment by ann0see** [comment]
The standard mastodon iOS app does the selection process quite well. Maybe have a look at that.
