### ISSUE TITLE
[BUG] Share button is non-functional.

### ISSUE THREAD

**Issue by HrBingR** [gkasdorf/memmy#40]
**Describe the bug**
When in a post the share button to share the post doesn't work.

**To Reproduce**
1. Tap on any post in the feed to go to the comments.
2. Tap the share button.
3. Nothing happens.

**Expected behavior**
Should be able to share a link to the post.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.0 Developer Beta
 - Version 0.0.1 (19)

**Logs:**
N/A

**Additional context**
N/A

**Comment by gkasdorf** [comment]
Done.
