### ISSUE TITLE
[Feature Requst] Displaying and navigate to subscribed communities in side-menu

### ISSUE THREAD

**Issue by HrBingR** [gkasdorf/memmy#42]
**Is your feature request related to a problem? Please describe.**
The list of subscribed communities is hidden behind the "Hot" button at the top, which can be confusing.

**Describe the solution you'd like**
I'd like a side-menu that can be accessed either via tab or swipe to access the list of subscribed communities, similar to how one would access subscribed subreddits in Apollo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gkasdorf** [comment]
Button added to allow for this in the feed view as well as under Profile. Thanks for the feedback!
