### ISSUE TITLE
[BUG] Status bar not visible

### ISSUE THREAD

**Issue by Julime** [gkasdorf/memmy#43]
**Describe the bug**
after rotating the phone, statusbar disappears

**To Reproduce**
1. Open the App
2. Hold phone in landscape
3. Hold phone vertical

Expected behavior
The statusbar should contain the usual objects: clock, signal strength, battery etc.

**Screenshots**

![grafik](https://github.com/gkasdorf/memmy/assets/7944656/8a85583e-5cdf-4539-86fd-0a06f44d50ea)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS16.5

**Comment by gkasdorf** [comment]
Hmm that's weird. Does switching between system dark/light mode change this?

**Comment by Julime** [comment]
Switching to light mode does not change this behavior. Tested after bug appeared and before.

**Comment by gkasdorf** [comment]
I'll investigate this later. Thanks for letting me know!

**Comment by gkasdorf** [comment]
> **Describe the bug** after rotating the phone, statusbar disappears
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Open the App
> 
>     2. Hold phone in landscape
> 
>     3. Hold phone vertical
> 
> 
> Expected behavior The statusbar should contain the usual objects: clock, signal strength, battery etc.
> 
> **Screenshots**
> 
> ![grafik](https://user-images.githubusercontent.com/7944656/246039876-8a85583e-5cdf-4539-86fd-0a06f44d50ea.png)
> 
> **Smartphone (please complete the following information):**
> 
>     * Device: iPhone 12 Pro
> 
>     * OS: iOS16.5

Can you report on if this is still happening in latest release?

**Comment by Julime** [comment]
Seems fixed!
