### ISSUE TITLE
[BUG] Save button is non-functional.

### ISSUE THREAD

**Issue by MMeldrum** [gkasdorf/memmy#44]
**Describe the bug**
When in a post the Save button to save the post doesn't work.

**To Reproduce**
1. Tap on any post in the feed to go to the comments.
2. Tap the Save button.
3. Nothing happens.

**Expected behavior**
Should be able to save the post.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 16.5
 - Version 0.0.1(19)

**Logs:**
N/A

**Additional context**
N/A

**Comment by gkasdorf** [comment]
This is finished. Will be in next update.
