### ISSUE TITLE
Apollo-like comment options

### ISSUE THREAD

**Issue by gkasdorf** [gkasdorf/memmy#5]
Use Apollo-like swipe gestures to reply to comments and to up/downvote comments.

- [x] Swipe to comment
- [x] Swipe to upvote
- [x] Swipe to downvote

**Comment by TysonCodes** [comment]
This seems to be buggy or perhaps there’s an independent bug. I find if I start upvoting a comment early in the post then scroll down other comments show the green upvote even though I didn’t upvote them. Refreshing the post sometimes shows an upvote sticking and sometimes clears it. I’m not sure exactly what is happening but it seems consistently wrong. 
Using 0.0.1 (17)

**Comment by TysonCodes** [comment]
Just noticed 19 is out and it’s still there. I’ll add an issue.
