### ISSUE TITLE
Please support Light Mode

### ISSUE THREAD

**Issue by lachlanhunt** [gkasdorf/memmy#52]
I know Dark Mode is trendy and popular, but it's just not comfortable for some people to read.

Please add support for Light Mode.

**Comment by gkasdorf** [comment]
Thanks. I've already begun some work on making it easy to switch between themes (more than just one dark and one light). I'll have this done soon.

**Comment by gkasdorf** [comment]
There is a light theme now (although it needs some tweaking and the option to use system default). Please report new issues about themes in a separate issue with the specific theme in question. Thanks.
