### ISSUE TITLE
Support for multiple accounts

### ISSUE THREAD

**Issue by infomofo** [gkasdorf/memmy#55]
**Is your feature request related to a problem? Please describe.**
Many reddit and other clients allow support for account switching.

**Describe the solution you'd like**
A way to stay logged into multiple accounts. Switching the accounts would change the home feed and the subscribed topics, and the account you post as.

**Describe alternatives you've considered**

**Additional context**

**Comment by gkasdorf** [comment]
I'm in the process of doing this now.

**Comment by gkasdorf** [comment]
Done.
