### ISSUE TITLE
[BUG] Unable to scroll through subscribed communities

### ISSUE THREAD

**Issue by HrBingR** [gkasdorf/memmy#61]
**Describe the bug**
Whether viewing subscribed communities via the new Profile tab at the bottom, or by tapping the Star icon in the top-left while on the Feeds tab, I am unable to scroll through the list, so am limited to the first n communities that I’m subscribed to. 

**To Reproduce**
1. Tap the star icon on the feeds tab, or go to the profile tab
2. Try to scroll

**Expected behavior**
I should be able to scroll through my subscribed communities if the number of communities subscribed to exceeds what fits on the screen at once.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone [13 Pro]
 - OS: [iOS 17.0 Developer Beta]
 - Version [0.0.1 (33)]

**Logs:**
N/A

**Additional context**
N/A

**Comment by gkasdorf** [comment]
Thanks. Will fix now.

**Comment by gkasdorf** [comment]
That was fast 🤘 https://github.com/gkasdorf/memmy/commit/1fbaed238ff3be615b6780972e3c82f9c8707de5

**Comment by gkasdorf** [comment]
Fix being released now. Enjoy and happy scrolling!
