### ISSUE TITLE
[BUG] new sorting lrder doesnt show

### ISSUE THREAD

**Issue by MalcolmMielle** [gkasdorf/memmy#65]
When looking at a community (e.g. beehaw technology), sorting by new stays at sorting by hot.

Open a community, press the symbol on the top right, click new, it refreshes but the order is the same

**Comment by gkasdorf** [comment]
I'll adjust that. Can you tell if the content changes and just the button icon doesn't change, or is the order the same regardless?

**Comment by MalcolmMielle** [comment]
The order and the button stay the same :)

**Comment by gkasdorf** [comment]
Should be fixed here, let me know if you still experience it. https://github.com/gkasdorf/memmy/pull/67

**Comment by gkasdorf** [comment]
So it looks like the button does update correctly now and the feed index works properly (although I should add some loading indicator, it's a bit awkward right now).

However I noticed an edge case last night where I was able to change the sort in a community but the community did not update. Worked normally but I ran into this. I'll look into it more.

Regardless, it should be about 95% functional now 😬

**Comment by gkasdorf** [comment]
I'm going to close this for now just for organization, but this is on my list of things to look into. I'm not 100% convinced it is fixed, but it appears to be from my testing (in the upcoming update). PLEASE let me know if you see this happen again and I'll investigate further. Appreciate the feedback!

**Comment by MalcolmMielle** [comment]
Fixed for me! Thanks!
