### ISSUE TITLE
[BUG] error screen does not match theme

### ISSUE THREAD

**Issue by fireshaper** [gkasdorf/memmy#68]
**Describe the bug**
When the error screen about not loading posts is displayed it is white although the theme is set to dark. 

**To Reproduce**
1. See error screen

**Expected behavior**
Error screen should follow app theme

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS16 beta

**Comment by gkasdorf** [comment]
Which version are you running?

**Comment by gkasdorf** [comment]
This shouldn't be an issue anymore. I reworked the errors so you don't lose your progress in scrolling. Let me know if you still have any issues though.
