### ISSUE TITLE
[BUG] Should be able to swipe right to back out of a website

### ISSUE THREAD

**Issue by HrBingR** [gkasdorf/memmy#69]
**Describe the bug**
When browsing a Lemmy instance through Memmy, you're able to swipe right to leave a post and go back to the main feed, but for links to websites that open an in-app browser window, you can't swipe right and instead have to tap the Done button to exit the window.

**To Reproduce**
1. Go to main feed.
2. Tap any link to open the browser modal.
3. Try to swipe right to exit.

**Expected behavior**
Should be able to swipe right to exit the browser modal.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone [13 Pro]
 - OS: [iOS 17.0 Developer Beta]
 - Version [0.0.1 35]

**Logs:**
N/A

**Additional context**
Apologies if this is more of a feature request, I logged it as a bug as I see it as an expected behavior based on other iOS apps, and the fact that you can swipe back frrom a post to the main feed.

**Comment by gkasdorf** [comment]
Don't believe it is possible with the pop-up browser. I will implement a webview screen so that we can get this functionality.

**Comment by gkasdorf** [comment]
Fixed. Will release tonight.
