### ISSUE TITLE
[BUG] images thumbnail(?) aspect ratios are messed up

### ISSUE THREAD

**Issue by b-bayport** [gkasdorf/memmy#71]
**Describe the bug**
On the main feed, seeing image posts being "narrow" and right-justified with most of display area being empty. Clicking on the post seeing that most are portrait mode images but a few are also landscape. Probably an aspect ratio thing. 

**To Reproduce**
1. Example post with a portrait pic: https://lemmy.world/post/221992

2. Example post with landscape pic with an odd aspect ratio: https://lemmy.ca/post/713540

**Expected behavior**
In the main feed screen, image previews would resized to coherently display a reasonable and center-justified preview.  

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/121366909/d85b9d88-c371-4a8c-aa59-a6eb9bb5f9a3)
![image](https://github.com/gkasdorf/memmy/assets/121366909/1247f77d-1e75-4488-974d-8dfca26c87e3)
![image](https://github.com/gkasdorf/memmy/assets/121366909/ee4415b6-f124-4ea6-bc6e-ba2cc62a6f65)
![image](https://github.com/gkasdorf/memmy/assets/121366909/c483dfc5-5308-4856-aded-d696398c7287)

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS 16.5
 - Version 0.0.1(35)

**Additional context**
Thank you! 🙏#gratitude

**Comment by gkasdorf** [comment]
So I've made some changes here that might help: https://github.com/gkasdorf/memmy/pull/75

Update will be available by tomorrow morning. Once you update, can you please let me know if you are still having this issue? Thanks!

**Comment by b-bayport** [comment]
This is resolved. Image preview/thumbnails are looking really good now with the latest release. Thank you
