### ISSUE TITLE
[BUG] Top middle is showing sort order instead of type of feed. There is already an icon on the top bar showing the sort type

### ISSUE THREAD

**Issue by ManikandanUV** [gkasdorf/memmy#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone [model]

**Logs:**
If you wish to submit any debug logs, you may do so by doing the following:
 - Navigate to Settings
 - Tap version number 5 times
 - Press "Send Logs"

This will open an email in your mail app with the logs in the body of the email. 

If you want, you can post them here. However, although there should not be any PII inside of the logs, it may be best to just send them privately. If you do want to post them here, please either find and provide the applicable parts of the logs, or check them for any PII.

**Additional context**

**Comment by gkasdorf** [comment]
Yea, I'm going to switch that. The dropdown is actually going to be the current account you are using.

**Comment by gkasdorf** [comment]
This is irrelevant now, used for account switching now. Thanks though! https://github.com/gkasdorf/memmy/pull/77
