### ISSUE TITLE
[MEM-85] View resets after rotating phone

### ISSUE THREAD

**Issue by Julime** [gkasdorf/memmy#78]
Whin rotating phone the feed reloads and is back at the top

**To Reproduce**
1. Open app
2. scroll down
3. (optional) view post
4. rotate phone

**Expected behavior**
I should see what i saw before rotating

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5

<sub>[MEM-85](https://linear.app/memmyapp/issue/MEM-85/view-resets-after-rotating-phone)</sub>

**Comment by b-bayport** [comment]
I experienced similar

**Comment by gkasdorf** [comment]
I see what's happening with this. Looks like it only affects the post screen. A few things need to be memoized. I'll work on this sooner than later. Thanks.

**Comment by gkasdorf** [comment]
I'm going to close this since there are some other issues about it, and because it isn't as specific as those. I am going to work on this though, so don't think it's going ignored.
