### ISSUE TITLE
Pure Black Dark Mode.

### ISSUE THREAD

**Issue by acdoe98** [gkasdorf/memmy#83]
The current “Dark” theme is a terrible brown/grey mix which just seems out of place and ugly on iOS. Would be best have a true “Black” dark mode as default and even a “OLED Black” mode available. 

Original:
![image](https://github.com/gkasdorf/memmy/assets/127624738/eed15724-cf10-4914-ade4-608697c2e156)

“Dark” & “OLED Black” modes. 
![image](https://github.com/gkasdorf/memmy/assets/127624738/72c2ec34-11d5-4b80-80b5-b8416bc58f2c)
![image](https://github.com/gkasdorf/memmy/assets/127624738/2a181cb7-2b92-4226-bf1a-c4fc4b634719)

**Comment by dtackgrounded** [comment]
They mentioned that Themes are on the roadmap, which included an all black theme. You can see examples on !memmy@lemmy.ml

**Comment by acdoe98** [comment]
Latest TestFlight build noted different colours schemes for dark mode will be available when themes are launched into Memmy.
