### ISSUE TITLE
[BUG] Community header  instance name

### ISSUE THREAD

**Issue by b-bayport** [gkasdorf/memmy#86]
**Describe the bug**
When viewing a lemmy community, the top header bar is not tall enough and cuts off the underlying instance name. 
See screenshot. 

**Expected behavior**
Be able to see both the community and instance names. 

Ideally be able to see the community's sidebar 

**Screenshots**
![image](https://github.com/gkasdorf/memmy/assets/121366909/c0d4ba1e-bba4-41ab-9ee2-7899fe7ac26b)

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS16.5
 - Version 0.0.1(35)

**Comment by adjoseph16** [comment]
Just fyi, looks like this is tied to the “Dynamic Type” text sizing:

![IMG_6926](https://github.com/gkasdorf/memmy/assets/78319881/43be4a3c-38f6-4089-99ae-1e32da1d9cf6)
![IMG_6925](https://github.com/gkasdorf/memmy/assets/78319881/b33917f5-ea11-4775-a472-e98067472a4a)
![IMG_6927](https://github.com/gkasdorf/memmy/assets/78319881/50f5dc96-8210-4fe5-8b95-8c827d9bd5a1)
![IMG_6928](https://github.com/gkasdorf/memmy/assets/78319881/35b1ca62-482a-4ac8-a56e-3bd9a143dc8e)

**Comment by gkasdorf** [comment]
Ah interesting. I didn't even consider that.

It won't be an issue in future updates anyway, as I will be changing the design of this screen. That information will be available in the header section of the list. But good to remember to pay attention to scale issues.

Question: from a user standpoint, would you care if that particular item didn't scale regardless of your setting? Main issue I see is accessibility issues though, so it wouldn't be optimal.

**Comment by gkasdorf** [comment]
Definitely should take it into account. I should probably add a slider in the app itself to adjust font scaling. Will be available with the redesign I am working on.

Thanks for the info! Take care
