### ISSUE TITLE
[BUG] JSON parse error with "<" character in password

### ISSUE THREAD

**Issue by joshtch** [gkasdorf/memmy#87]
**Describe the bug**
When I entered my password, which had a "<" character in it, I got an error message as seen in the picture below. 

**To Reproduce**
1. Create an account with (or change password on an existing account to) a password that has the "less than" symbol (<)
2. In Memmy, try to log in to this account. 

**Expected behavior**
You successfully log into your account, same as would happen if your password didn't contain the "<" character. 

**Screenshots**
![Failure message](https://github.com/gkasdorf/memmy/assets/4016526/5cc30d9b-d384-43c1-b901-8d57b28d5401)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5
 - Version 45

**Comment by gkasdorf** [comment]
Right now Kbin is not supported. I've been going over the API and believe I can do a pretty seamless integration, so that's on the list to do once I get things ironed out as is.

**Comment by aaomidi** [comment]
Is there an issue tracking kbin integration?
