### ISSUE TITLE
[BUG] Community screen not showing all posts

### ISSUE THREAD

**Issue by z01L** [gkasdorf/memmy#93]
**Describe the bug**
When viewing a community(eg. football@lemmy.world), only posts from the last 24 hours are shown.

**To Reproduce**
1. On the main feed, Click on the community name on a post
2. Scroll down through the community
3. Not all posts in the community are shown, only posts from the past 24 hours(as far as I can tell)

**Expected behavior**
You can scroll through all posts on the community, with posts loading as you scroll down based on the sorting you’ve selected.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.5
 - Version 0.0.1(47)

**Comment by gkasdorf** [comment]
Are you using Top Day? I've noticed this when using that sort option.

**Comment by z01L** [comment]
🤦‍♂️ I had Top Day as my default sort order and didn’t realise that the sort in community will default to it(I had changed it to new on my main feed).

Mark this down as user error.
