### ISSUE TITLE
[MEM-90] Scale thumbnail images dynamically to fill width of screen.

### ISSUE THREAD

**Issue by hugpeter** [gkasdorf/memmy#99]
People post images of all kinds of aspect ratios. Currently, Memmy handles this by using the blank bars on the sides if that side isn't tall or wide enough.

Example:

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/aae402f1-5fa5-4901-8c71-b8b50e176654/d1806c4f-8876-447d-9c43-aa0952e3c9f4)

If we could have it zoom in or out so that the width hits both sides, and let the header and footer of the post dynamically adjust to the resulting height of the thumbnail.

Example from mlem:

![](https://uploads.linear.app/7655b776-38c4-4273-b069-78045fe3cd9c/ddd8b377-625c-4911-9548-b1ba93317864/beb9054f-28ec-4669-ad0d-9d4b3f06db79)

<sub>From [SyncLinear.com](https://synclinear.com) | [MEM-90](https://linear.app/memmyapp/issue/MEM-90/scale-thumbnail-images-dynamically-to-fill-width-of-screen)</sub>

**Comment by gkasdorf** [comment]
One of these days (probably this week) I'll be forking the lib that I use to handle those. The animations are okay at best and I don't like the way it handles image sizes. Don't worry, it annoys me too and will be dealt with. Thanks!

**Comment by gkasdorf** [comment]
I think what you were requesting here has been implemented. Feel free to reopen if there's something I missed.
